apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# patches:
# - target:
#     kind: Service
#     name: demo-dry-flo
#   patch: |-
#     - op: replace
#       path: /metadata/labels/backstage.io/kubernetes-id
#       value: demo-dry-flo-prod